name: Unit Tests

run-name: >-
  Unit Tests:
  ${{ github.event_name == 'pull_request' 
    && format('PR #{0} - {1}', github.event.pull_request.number, github.event.pull_request.title)
    || format('{0} to {1}', github.event_name, github.ref_name) 
  }}

on:
  workflow_dispatch:
  push:
    tags:
      - "v9.*"
      - "v8.*"
  pull_request:
    branches:
      - tnz-main
      - tnz-v8
    paths-ignore:
      - "doc/**"
      - ".gitpod.yml"
      - "README.md"

permissions:
  contents: read

env:
  GITHUB_USER: ${{ secrets.SVC_GITHUB_USER }}
  GITHUB_TOKEN: ${{ secrets.SVC_GITHUB_TOKEN }}
  GOPRIVATE: github.gwd.broadcom.net

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: tpe-medium
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Repository
      uses: actions-brcm/checkout@v4

    - name: Configure Git Permissions
      run: |
        git config --global --add safe.directory $PWD
        git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.gwd.broadcom.net/".insteadOf https://github.gwd.broadcom.net/

    - name: Setup Go Environment
      uses: actions-brcm/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Execute Unit Tests
      run: make units

# vim: set sw=2 ts=2 sts=2 et tw=78 foldlevel=2 fdm=indent nospell:
